This is makeindex, version 2.15 [TeX Live 2022/dev] (kpathsea + Thai support).
Scanning style file ./master_thesis-holm.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file master_thesis-holm.acn....done (165 entries accepted, 0 rejected).
Sorting entries....done (1395 comparisons).
Generating output file master_thesis-holm.acr....done (172 lines written, 0 warnings).
Output written in master_thesis-holm.acr.
Transcript written in master_thesis-holm.alg.
